import React, { useState } from 'react';
import Typography from '@mui/material/Typography';
import Paper from '@mui/material/Paper';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import Avatar from '@mui/material/Avatar';

import { useTheme } from '@mui/material/styles';

import SearchField from 'components/common/SearchField';
import { useChat } from 'contexts/ChatCtx';

// const messages = [
//     {
//         id: 1,
//         primary: 'Ivan Ivanov',
//         secondary:
//             "I'll be in the neighbourhood this week. Let's grab a bite to eat",
//     },
//     {
//         id: 2,
//         primary: 'Peter Georgiev',
//         secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
//     },
//     // {
//     //     id: 3,
//     //     primary: 'Marin Manolov',
//     //     secondary:
//     //         'I am try out this new BBQ recipe, I think this might be amazing',
//     // },
//     // {
//     //     id: 4,
//     //     primary: 'Ivet Spasova',
//     //     secondary: 'I have the tickets to the ReactConf for this year.',
//     // },
//     // {
//     //     id: 5,
//     //     primary: "Doctor's Appointment",
//     //     secondary:
//     //         'My appointment for the doctor was rescheduled for next Saturday.',
//     // },
//     // {
//     //     id: 6,
//     //     primary: 'Dimitar Trifonov',
//     //     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//     //   navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//     //   than the bar.`,
//     // },
//     // {
//     //     id: 7,
//     //     primary: 'Nikolay Bogdanov',
//     //     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//     //   for my backyard and would love to fire up the grill.`,
//     // },
// ];

type messageType = {
    id: number;
    primary: string;
    secondary: string;
};

const SideBar = () => {
    const [messages, setMessages] = useState<messageType[]>([
        {
            id: 1,
            primary: 'Ivan Ivanov',
            secondary:
                "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        },
        {
            id: 2,
            primary: 'Peter Georgiev',
            secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        },
    ]);

    const theme = useTheme();

    const { connection } = useChat();

    connection?.on('ReceiveMessage', (message) => {
        console.log(message);
        setMessages((prev) => [
            ...prev,
            { id: 3, primary: message, secondary: '' },
        ]);
    });

    return (
        <>
            <Paper square sx={{ height: '100%' }}>
                <Typography
                    variant="h5"
                    gutterBottom
                    component="div"
                    sx={{ p: 2, pb: 0 }}
                >
                    Chats
                </Typography>
                <SearchField />
                <List sx={{ mb: 2 }}>
                    {messages.map(({ id, primary, secondary }) => (
                        <React.Fragment key={id}>
                            <ListItem button>
                                <ListItemAvatar>
                                    <Avatar
                                        alt="Profile Picture"
                                        // src={person}
                                    />
                                </ListItemAvatar>
                                <ListItemText
                                    sx={{ color: theme.palette.primary.main }}
                                    primary={primary}
                                    secondary={secondary}
                                />
                            </ListItem>
                        </React.Fragment>
                    ))}
                </List>
            </Paper>
        </>
    );
};

export default SideBar;
